# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: faro/proto/face_service.proto for package ''
# Original file comments:
#
# MIT License
#
# Copyright 2019 Oak Ridge National Laboratory
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

require 'grpc'
require 'faro/proto/face_service_pb'

module FaceRecognition
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'FaceRecognition'

    # Service info and defaults
    rpc :status, FaceStatusRequest, FaceServiceInfo
    # Simple operations
    rpc :detect, DetectRequest, FaceRecordList
    rpc :extract, ExtractRequest, FaceRecordList
    rpc :score, ScoreRequest, Matrix
    rpc :enroll, EnrollRequest, FaceRecordList
    rpc :search, SearchRequest, FaceRecordList
    # Combined opperations
    rpc :detectExtract, DetectExtractRequest, FaceRecordList
    rpc :detectExtractEnroll, DetectExtractEnrollRequest, FaceRecordList
    rpc :detectExtractSearch, DetectExtractSearchRequest, FaceRecordList
    # Gallery Management
    rpc :galleryList, GalleryListRequest, GalleryList
    rpc :galleryDelete, GalleryDeleteRequest, Empty
    rpc :enrollmentList, EnrollmentListRequest, FaceRecordList
    rpc :enrollmentDelete, EnrollmentDeleteRequest, FaceRecordList
    rpc :enrollmentDeleteConditional, EnrollmentDeleteRequest, FaceRecordList
    rpc :enrollmentTransfer, EnrollmentDeleteRequest, FaceRecordList
    # Test
    rpc :echo, Matrix, Matrix
  end

  Stub = Service.rpc_stub_class
end
