<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *This is intended to support flexible encoding schemes in a dictionary like structure:
 *Example encodings: MALE:0.975, AGE:35.2, RACE:WHITE 
 *
 * Generated from protobuf message <code>Attribute</code>
 */
class Attribute extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    private $key = '';
    /**
     * A text description on the content or type hint
     *
     * Generated from protobuf field <code>string description = 2;</code>
     */
    private $description = '';
    /**
     * Typically popualate only one of these values
     *
     * Generated from protobuf field <code>bytes buffer = 3;</code>
     */
    private $buffer = '';
    /**
     * Generated from protobuf field <code>float fvalue = 4;</code>
     */
    private $fvalue = 0.0;
    /**
     * Generated from protobuf field <code>int32 ivalue = 5;</code>
     */
    private $ivalue = 0;
    /**
     * Generated from protobuf field <code>string text = 6;</code>
     */
    private $text = '';
    /**
     * Generated from protobuf field <code>bytes pickle = 7;</code>
     */
    private $pickle = '';
    /**
     * Generated from protobuf field <code>bytes json = 8;</code>
     */
    private $json = '';
    /**
     * Generated from protobuf field <code>.Matrix matrix = 9;</code>
     */
    private $matrix = null;
    /**
     * Generated from protobuf field <code>.Vector vector = 10;</code>
     */
    private $vector = null;
    /**
     * Generated from protobuf field <code>.Image image = 11;</code>
     */
    private $image = null;
    /**
     * Generated from protobuf field <code>.Point2D point = 12;</code>
     */
    private $point = null;
    /**
     * Generated from protobuf field <code>.Rect rect = 13;</code>
     */
    private $rect = null;
    /**
     * Generated from protobuf field <code>bytes xml = 14;</code>
     */
    private $xml = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $description
     *           A text description on the content or type hint
     *     @type string $buffer
     *           Typically popualate only one of these values
     *     @type float $fvalue
     *     @type int $ivalue
     *     @type string $text
     *     @type string $pickle
     *     @type string $json
     *     @type \Matrix $matrix
     *     @type \Vector $vector
     *     @type \Image $image
     *     @type \Point2D $point
     *     @type \Rect $rect
     *     @type string $xml
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\FaceService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * A text description on the content or type hint
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * A text description on the content or type hint
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Typically popualate only one of these values
     *
     * Generated from protobuf field <code>bytes buffer = 3;</code>
     * @return string
     */
    public function getBuffer()
    {
        return $this->buffer;
    }

    /**
     * Typically popualate only one of these values
     *
     * Generated from protobuf field <code>bytes buffer = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBuffer($var)
    {
        GPBUtil::checkString($var, False);
        $this->buffer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float fvalue = 4;</code>
     * @return float
     */
    public function getFvalue()
    {
        return $this->fvalue;
    }

    /**
     * Generated from protobuf field <code>float fvalue = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setFvalue($var)
    {
        GPBUtil::checkFloat($var);
        $this->fvalue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ivalue = 5;</code>
     * @return int
     */
    public function getIvalue()
    {
        return $this->ivalue;
    }

    /**
     * Generated from protobuf field <code>int32 ivalue = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setIvalue($var)
    {
        GPBUtil::checkInt32($var);
        $this->ivalue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 6;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes pickle = 7;</code>
     * @return string
     */
    public function getPickle()
    {
        return $this->pickle;
    }

    /**
     * Generated from protobuf field <code>bytes pickle = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPickle($var)
    {
        GPBUtil::checkString($var, False);
        $this->pickle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes json = 8;</code>
     * @return string
     */
    public function getJson()
    {
        return $this->json;
    }

    /**
     * Generated from protobuf field <code>bytes json = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setJson($var)
    {
        GPBUtil::checkString($var, False);
        $this->json = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Matrix matrix = 9;</code>
     * @return \Matrix
     */
    public function getMatrix()
    {
        return $this->matrix;
    }

    /**
     * Generated from protobuf field <code>.Matrix matrix = 9;</code>
     * @param \Matrix $var
     * @return $this
     */
    public function setMatrix($var)
    {
        GPBUtil::checkMessage($var, \Matrix::class);
        $this->matrix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Vector vector = 10;</code>
     * @return \Vector
     */
    public function getVector()
    {
        return $this->vector;
    }

    /**
     * Generated from protobuf field <code>.Vector vector = 10;</code>
     * @param \Vector $var
     * @return $this
     */
    public function setVector($var)
    {
        GPBUtil::checkMessage($var, \Vector::class);
        $this->vector = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Image image = 11;</code>
     * @return \Image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Generated from protobuf field <code>.Image image = 11;</code>
     * @param \Image $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkMessage($var, \Image::class);
        $this->image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Point2D point = 12;</code>
     * @return \Point2D
     */
    public function getPoint()
    {
        return $this->point;
    }

    /**
     * Generated from protobuf field <code>.Point2D point = 12;</code>
     * @param \Point2D $var
     * @return $this
     */
    public function setPoint($var)
    {
        GPBUtil::checkMessage($var, \Point2D::class);
        $this->point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Rect rect = 13;</code>
     * @return \Rect
     */
    public function getRect()
    {
        return $this->rect;
    }

    /**
     * Generated from protobuf field <code>.Rect rect = 13;</code>
     * @param \Rect $var
     * @return $this
     */
    public function setRect($var)
    {
        GPBUtil::checkMessage($var, \Rect::class);
        $this->rect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes xml = 14;</code>
     * @return string
     */
    public function getXml()
    {
        return $this->xml;
    }

    /**
     * Generated from protobuf field <code>bytes xml = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setXml($var)
    {
        GPBUtil::checkString($var, False);
        $this->xml = $var;

        return $this;
    }

}

