<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DetectExtractSearchRequest</code>
 */
class DetectExtractSearchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.DetectRequest detect_request = 1;</code>
     */
    private $detect_request = null;
    /**
     * The image and face list are replaced by the result of the detect results.
     *
     * Generated from protobuf field <code>.ExtractRequest extract_request = 2;</code>
     */
    private $extract_request = null;
    /**
     * The face list is replaced by the result of the extract results.
     *
     * Generated from protobuf field <code>.SearchRequest search_request = 3;</code>
     */
    private $search_request = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \DetectRequest $detect_request
     *     @type \ExtractRequest $extract_request
     *           The image and face list are replaced by the result of the detect results.
     *     @type \SearchRequest $search_request
     *           The face list is replaced by the result of the extract results.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\FaceService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.DetectRequest detect_request = 1;</code>
     * @return \DetectRequest
     */
    public function getDetectRequest()
    {
        return $this->detect_request;
    }

    /**
     * Generated from protobuf field <code>.DetectRequest detect_request = 1;</code>
     * @param \DetectRequest $var
     * @return $this
     */
    public function setDetectRequest($var)
    {
        GPBUtil::checkMessage($var, \DetectRequest::class);
        $this->detect_request = $var;

        return $this;
    }

    /**
     * The image and face list are replaced by the result of the detect results.
     *
     * Generated from protobuf field <code>.ExtractRequest extract_request = 2;</code>
     * @return \ExtractRequest
     */
    public function getExtractRequest()
    {
        return $this->extract_request;
    }

    /**
     * The image and face list are replaced by the result of the detect results.
     *
     * Generated from protobuf field <code>.ExtractRequest extract_request = 2;</code>
     * @param \ExtractRequest $var
     * @return $this
     */
    public function setExtractRequest($var)
    {
        GPBUtil::checkMessage($var, \ExtractRequest::class);
        $this->extract_request = $var;

        return $this;
    }

    /**
     * The face list is replaced by the result of the extract results.
     *
     * Generated from protobuf field <code>.SearchRequest search_request = 3;</code>
     * @return \SearchRequest
     */
    public function getSearchRequest()
    {
        return $this->search_request;
    }

    /**
     * The face list is replaced by the result of the extract results.
     *
     * Generated from protobuf field <code>.SearchRequest search_request = 3;</code>
     * @param \SearchRequest $var
     * @return $this
     */
    public function setSearchRequest($var)
    {
        GPBUtil::checkMessage($var, \SearchRequest::class);
        $this->search_request = $var;

        return $this;
    }

}

