<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ********* Enrollment Management *******
 *
 * Generated from protobuf message <code>EnrollmentListRequest</code>
 */
class EnrollmentListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string gallery_name = 1;</code>
     */
    private $gallery_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gallery_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\FaceService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string gallery_name = 1;</code>
     * @return string
     */
    public function getGalleryName()
    {
        return $this->gallery_name;
    }

    /**
     * Generated from protobuf field <code>string gallery_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGalleryName($var)
    {
        GPBUtil::checkString($var, True);
        $this->gallery_name = $var;

        return $this;
    }

}

