<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>EnrollRequest</code>
 */
class EnrollRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string enroll_gallery = 1;</code>
     */
    private $enroll_gallery = '';
    /**
     * Generated from protobuf field <code>.FaceRecordList records = 2;</code>
     */
    private $records = null;
    /**
     * Generated from protobuf field <code>.EnrollOptions enroll_options = 10;</code>
     */
    private $enroll_options = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $enroll_gallery
     *     @type \FaceRecordList $records
     *     @type \EnrollOptions $enroll_options
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\FaceService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string enroll_gallery = 1;</code>
     * @return string
     */
    public function getEnrollGallery()
    {
        return $this->enroll_gallery;
    }

    /**
     * Generated from protobuf field <code>string enroll_gallery = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEnrollGallery($var)
    {
        GPBUtil::checkString($var, True);
        $this->enroll_gallery = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FaceRecordList records = 2;</code>
     * @return \FaceRecordList
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>.FaceRecordList records = 2;</code>
     * @param \FaceRecordList $var
     * @return $this
     */
    public function setRecords($var)
    {
        GPBUtil::checkMessage($var, \FaceRecordList::class);
        $this->records = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.EnrollOptions enroll_options = 10;</code>
     * @return \EnrollOptions
     */
    public function getEnrollOptions()
    {
        return $this->enroll_options;
    }

    /**
     * Generated from protobuf field <code>.EnrollOptions enroll_options = 10;</code>
     * @param \EnrollOptions $var
     * @return $this
     */
    public function setEnrollOptions($var)
    {
        GPBUtil::checkMessage($var, \EnrollOptions::class);
        $this->enroll_options = $var;

        return $this;
    }

}

