<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ExtractRequest</code>
 */
class ExtractRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Image image = 1;</code>
     */
    private $image = null;
    /**
     * Generated from protobuf field <code>.FaceRecordList records = 4;</code>
     */
    private $records = null;
    /**
     * Generated from protobuf field <code>.ExtractOptions extract_options = 9;</code>
     */
    private $extract_options = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Image $image
     *     @type \FaceRecordList $records
     *     @type \ExtractOptions $extract_options
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\FaceService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Image image = 1;</code>
     * @return \Image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Generated from protobuf field <code>.Image image = 1;</code>
     * @param \Image $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkMessage($var, \Image::class);
        $this->image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FaceRecordList records = 4;</code>
     * @return \FaceRecordList
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>.FaceRecordList records = 4;</code>
     * @param \FaceRecordList $var
     * @return $this
     */
    public function setRecords($var)
    {
        GPBUtil::checkMessage($var, \FaceRecordList::class);
        $this->records = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ExtractOptions extract_options = 9;</code>
     * @return \ExtractOptions
     */
    public function getExtractOptions()
    {
        return $this->extract_options;
    }

    /**
     * Generated from protobuf field <code>.ExtractOptions extract_options = 9;</code>
     * @param \ExtractOptions $var
     * @return $this
     */
    public function setExtractOptions($var)
    {
        GPBUtil::checkMessage($var, \ExtractOptions::class);
        $this->extract_options = $var;

        return $this;
    }

}

