<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FaceRecordList</code>
 */
class FaceRecordList extends \Google\Protobuf\Internal\Message
{
    /**
     *repeated float scores = 2; // Scores returned by gallery searches
     *
     * Generated from protobuf field <code>repeated .FaceRecord face_records = 1;</code>
     */
    private $face_records;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \FaceRecord[]|\Google\Protobuf\Internal\RepeatedField $face_records
     *          repeated float scores = 2; // Scores returned by gallery searches
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\FaceService::initOnce();
        parent::__construct($data);
    }

    /**
     *repeated float scores = 2; // Scores returned by gallery searches
     *
     * Generated from protobuf field <code>repeated .FaceRecord face_records = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFaceRecords()
    {
        return $this->face_records;
    }

    /**
     *repeated float scores = 2; // Scores returned by gallery searches
     *
     * Generated from protobuf field <code>repeated .FaceRecord face_records = 1;</code>
     * @param \FaceRecord[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFaceRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \FaceRecord::class);
        $this->face_records = $arr;

        return $this;
    }

}

