<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>MatchInfo</code>
 */
class MatchInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float score = 1;</code>
     */
    private $score = 0.0;
    /**
     * Generated from protobuf field <code>string image_id = 2;</code>
     */
    private $image_id = '';
    /**
     * Generated from protobuf field <code>string detection_id = 3;</code>
     */
    private $detection_id = '';
    /**
     * Generated from protobuf field <code>string subject_id = 4;</code>
     */
    private $subject_id = '';
    /**
     * Generated from protobuf field <code>string subject_name = 5;</code>
     */
    private $subject_name = '';
    /**
     * Generated from protobuf field <code>.Image face = 6;</code>
     */
    private $face = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $score
     *     @type string $image_id
     *     @type string $detection_id
     *     @type string $subject_id
     *     @type string $subject_name
     *     @type \Image $face
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\FaceService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float score = 1;</code>
     * @return float
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>float score = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkFloat($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string image_id = 2;</code>
     * @return string
     */
    public function getImageId()
    {
        return $this->image_id;
    }

    /**
     * Generated from protobuf field <code>string image_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setImageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->image_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string detection_id = 3;</code>
     * @return string
     */
    public function getDetectionId()
    {
        return $this->detection_id;
    }

    /**
     * Generated from protobuf field <code>string detection_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDetectionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->detection_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject_id = 4;</code>
     * @return string
     */
    public function getSubjectId()
    {
        return $this->subject_id;
    }

    /**
     * Generated from protobuf field <code>string subject_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSubjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject_name = 5;</code>
     * @return string
     */
    public function getSubjectName()
    {
        return $this->subject_name;
    }

    /**
     * Generated from protobuf field <code>string subject_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSubjectName($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Image face = 6;</code>
     * @return \Image
     */
    public function getFace()
    {
        return $this->face;
    }

    /**
     * Generated from protobuf field <code>.Image face = 6;</code>
     * @param \Image $var
     * @return $this
     */
    public function setFace($var)
    {
        GPBUtil::checkMessage($var, \Image::class);
        $this->face = $var;

        return $this;
    }

}

