<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

/**
 * Protobuf type <code>ScoreType</code>
 */
class ScoreType
{
    /**
     * Generated from protobuf enum <code>SERVER = 0;</code>
     */
    const SERVER = 0;
    /**
     * Generated from protobuf enum <code>L1 = 1;</code>
     */
    const L1 = 1;
    /**
     * Generated from protobuf enum <code>L2 = 2;</code>
     */
    const L2 = 2;
    /**
     * Generated from protobuf enum <code>NEG_DOT = 3;</code>
     */
    const NEG_DOT = 3;

    private static $valueToName = [
        self::SERVER => 'SERVER',
        self::L1 => 'L1',
        self::L2 => 'L2',
        self::NEG_DOT => 'NEG_DOT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

