<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * suggested : typically use TemplateLists because they are smaller. Then
 *             FaceRecordLists should be left empty.
 * FaceRecordsList can be used as a convieniance but may be too large,
 * slow, or use to much band with.
 *
 * Generated from protobuf message <code>ScoreRequest</code>
 */
class ScoreRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.FaceRecordList face_probes = 1;</code>
     */
    private $face_probes = null;
    /**
     * Generated from protobuf field <code>.FaceRecordList face_gallery = 2;</code>
     */
    private $face_gallery = null;
    /**
     * Generated from protobuf field <code>.TemplateList template_probes = 3;</code>
     */
    private $template_probes = null;
    /**
     * Generated from protobuf field <code>.TemplateList template_gallery = 4;</code>
     */
    private $template_gallery = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \FaceRecordList $face_probes
     *     @type \FaceRecordList $face_gallery
     *     @type \TemplateList $template_probes
     *     @type \TemplateList $template_gallery
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\FaceService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.FaceRecordList face_probes = 1;</code>
     * @return \FaceRecordList
     */
    public function getFaceProbes()
    {
        return $this->face_probes;
    }

    /**
     * Generated from protobuf field <code>.FaceRecordList face_probes = 1;</code>
     * @param \FaceRecordList $var
     * @return $this
     */
    public function setFaceProbes($var)
    {
        GPBUtil::checkMessage($var, \FaceRecordList::class);
        $this->face_probes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FaceRecordList face_gallery = 2;</code>
     * @return \FaceRecordList
     */
    public function getFaceGallery()
    {
        return $this->face_gallery;
    }

    /**
     * Generated from protobuf field <code>.FaceRecordList face_gallery = 2;</code>
     * @param \FaceRecordList $var
     * @return $this
     */
    public function setFaceGallery($var)
    {
        GPBUtil::checkMessage($var, \FaceRecordList::class);
        $this->face_gallery = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TemplateList template_probes = 3;</code>
     * @return \TemplateList
     */
    public function getTemplateProbes()
    {
        return $this->template_probes;
    }

    /**
     * Generated from protobuf field <code>.TemplateList template_probes = 3;</code>
     * @param \TemplateList $var
     * @return $this
     */
    public function setTemplateProbes($var)
    {
        GPBUtil::checkMessage($var, \TemplateList::class);
        $this->template_probes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.TemplateList template_gallery = 4;</code>
     * @return \TemplateList
     */
    public function getTemplateGallery()
    {
        return $this->template_gallery;
    }

    /**
     * Generated from protobuf field <code>.TemplateList template_gallery = 4;</code>
     * @param \TemplateList $var
     * @return $this
     */
    public function setTemplateGallery($var)
    {
        GPBUtil::checkMessage($var, \TemplateList::class);
        $this->template_gallery = $var;

        return $this;
    }

}

