<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TemplateList</code>
 */
class TemplateList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .FaceTemplate templates = 1;</code>
     */
    private $templates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \FaceTemplate[]|\Google\Protobuf\Internal\RepeatedField $templates
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\FaceService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .FaceTemplate templates = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTemplates()
    {
        return $this->templates;
    }

    /**
     * Generated from protobuf field <code>repeated .FaceTemplate templates = 1;</code>
     * @param \FaceTemplate[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTemplates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \FaceTemplate::class);
        $this->templates = $arr;

        return $this;
    }

}

