<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/geometry.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vector</code>
 */
class Vector extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated float data = 1 [packed = true];</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float[]|\Google\Protobuf\Internal\RepeatedField $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\Geometry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated float data = 1 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated float data = 1 [packed = true];</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->data = $arr;

        return $this;
    }

}

