<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/face_service.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>VerificationRequest</code>
 */
class VerificationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string gallery = 1;</code>
     */
    private $gallery = '';
    /**
     * Generated from protobuf field <code>string subject_id = 2;</code>
     */
    private $subject_id = '';
    /**
     * Generated from protobuf field <code>repeated .FaceRecord face_record = 3;</code>
     */
    private $face_record;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gallery
     *     @type string $subject_id
     *     @type \FaceRecord[]|\Google\Protobuf\Internal\RepeatedField $face_record
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faro\Proto\FaceService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string gallery = 1;</code>
     * @return string
     */
    public function getGallery()
    {
        return $this->gallery;
    }

    /**
     * Generated from protobuf field <code>string gallery = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGallery($var)
    {
        GPBUtil::checkString($var, True);
        $this->gallery = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject_id = 2;</code>
     * @return string
     */
    public function getSubjectId()
    {
        return $this->subject_id;
    }

    /**
     * Generated from protobuf field <code>string subject_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubjectId($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .FaceRecord face_record = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFaceRecord()
    {
        return $this->face_record;
    }

    /**
     * Generated from protobuf field <code>repeated .FaceRecord face_record = 3;</code>
     * @param \FaceRecord[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFaceRecord($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \FaceRecord::class);
        $this->face_record = $arr;

        return $this;
    }

}

