/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.EnrollmentListResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.EnrollmentInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.EnrollmentListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.EnrollmentListResponse.repeatedFields_, null);
};
goog.inherits(proto.EnrollmentListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.EnrollmentListResponse.displayName = 'proto.EnrollmentListResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.EnrollmentListResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.EnrollmentListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.EnrollmentListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.EnrollmentListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.EnrollmentListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    galleryName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    enrollmentsList: jspb.Message.toObjectList(msg.getEnrollmentsList(),
    proto.EnrollmentInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.EnrollmentListResponse}
 */
proto.EnrollmentListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.EnrollmentListResponse;
  return proto.EnrollmentListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.EnrollmentListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.EnrollmentListResponse}
 */
proto.EnrollmentListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGalleryName(value);
      break;
    case 2:
      var value = new proto.EnrollmentInfo;
      reader.readMessage(value,proto.EnrollmentInfo.deserializeBinaryFromReader);
      msg.addEnrollments(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.EnrollmentListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.EnrollmentListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.EnrollmentListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.EnrollmentListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGalleryName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEnrollmentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.EnrollmentInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string gallery_name = 1;
 * @return {string}
 */
proto.EnrollmentListResponse.prototype.getGalleryName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.EnrollmentListResponse.prototype.setGalleryName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated EnrollmentInfo enrollments = 2;
 * @return {!Array<!proto.EnrollmentInfo>}
 */
proto.EnrollmentListResponse.prototype.getEnrollmentsList = function() {
  return /** @type{!Array<!proto.EnrollmentInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.EnrollmentInfo, 2));
};


/** @param {!Array<!proto.EnrollmentInfo>} value */
proto.EnrollmentListResponse.prototype.setEnrollmentsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.EnrollmentInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.EnrollmentInfo}
 */
proto.EnrollmentListResponse.prototype.addEnrollments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.EnrollmentInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.EnrollmentListResponse.prototype.clearEnrollmentsList = function() {
  this.setEnrollmentsList([]);
};


