<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faro/proto/geometry.proto

namespace GPBMetadata\Faro\Proto;

class Geometry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe010a196661726f2f70726f746f2f67656f6d657472792e70726f746f" .
            "223b0a045265637412090a017818012001280212090a0179180220012802" .
            "120d0a057769647468180320012802120e0a066865696768741804200128" .
            "02221f0a07506f696e74324412090a017818012001280212090a01791802" .
            "20012802221a0a06566563746f7212100a04646174611801200328024202" .
            "1001221f0a064d617472697812150a04726f777318012003280b32072e56" .
            "6563746f72620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

